zarr_dir: ../data/processed/lid-driven
input_fields: pressure,vel_x,vel_y
output_fields: pressure,vel_x,vel_y
input_time_idx: 0
target_time_idx: -1
epochs: 20
batch_size: 4
num_workers: 0
lr: 0.001
seed: 42
device: auto
latent_channels: 32
num_fno_layers: 4
num_fno_modes: 12
padding: 5
decoder_layers: 1
decoder_layer_size: 32
output: ../data/models/lid_driven_fno.mdlus
